# Generated by Django 3.1.3 on 2020-11-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201116_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultanswer',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='answers',
            field=models.ManyToManyField(to='api.ResultAnswer'),
        ),
        migrations.AlterField(
            model_name='resultanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
    ]
