# Generated by Django 3.1.3 on 2020-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201116_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('multiple', 'Multiple')], default='multiple', max_length=12),
        ),
    ]
