# Generated by Django 3.1.3 on 2020-11-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='choice_with_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_four',
        ),
    ]
